import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import Button from "../components/button";
const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>StampTube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center  p-4">
        <h1 className="text-3xl">StampTube</h1>
        <p>A place for community submitted timestamps</p>
        <Button>Log in with Google</Button>
        <Button
          bgColor="bg-purple-400"
          onClickFunction={() => signIn("discord")}
        >
          Log in with Discord
        </Button>
      </main>
    </>
  );
};

export default Home;
